const DB_NAME="DealDhamakaAgent", DB_VER=1;
let db;
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random()}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{db=r.result;["contacts","products","history"].forEach(s=>{if(!db.objectStoreNames.contains(s))db.createObjectStore(s,{keyPath:"id"})})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function all(store){return new Promise((res,rej)=>{const t=db.transaction(store,"readonly");const r=t.objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,obj){return new Promise((res,rej)=>{const t=db.transaction(store,"readwrite");t.objectStore(store).put(obj);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
function del(store,id){return new Promise((res,rej)=>{const t=db.transaction(store,"readwrite");t.objectStore(store).delete(id);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
function clear(store){return new Promise((res,rej)=>{const t=db.transaction(store,"readwrite");t.objectStore(store).clear();t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}

function showPage(name){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===name));document.querySelectorAll(".tabbar button").forEach(x=>x.classList.toggle("active",x.dataset.page===name));render(name)}
async function render(page){
 const [cs,ps,hs]=await Promise.all([all("contacts"),all("products"),all("history")]);
 $("contactCount").textContent=cs.length;$("productCount").textContent=ps.length;$("sentCount").textContent=hs.length;
 if(page==="contacts")renderContacts(cs); if(page==="products")renderProducts(ps); if(page==="send")await renderSend(cs,ps); if(page==="history")renderHistory(hs);
}
function renderContacts(cs){let q=$("contactSearch").value.toLowerCase();let a=cs.filter(x=>(x.name+" "+x.phone).toLowerCase().includes(q));$("contactsList").innerHTML=a.length?a.map(x=>`<div class="item"><div><h3>${esc(x.name)}</h3><p>WhatsApp: ${esc(x.phone)}</p><p>${esc(x.category||"General")}</p></div><div class="actions"><button class="mini" onclick="editContact('${x.id}')">Edit</button><button class="mini" onclick="deleteContact('${x.id}')">Delete</button></div></div>`).join(""):`<div class="empty">No contacts yet.<br>Add one or import a CSV.</div>`}
function renderProducts(ps){let q=$("productSearch").value.toLowerCase();let a=ps.filter(x=>(x.name+" "+x.platform+" "+x.link).toLowerCase().includes(q));$("productsList").innerHTML=a.length?a.map(x=>`<div class="item"><div><h3>${esc(x.name)}</h3><p>${esc(x.platform||"")}${x.price?" · ₹"+esc(x.price):""}</p><p>${esc(x.link)}</p></div><div class="actions"><button class="mini" onclick="editProduct('${x.id}')">Edit</button><button class="mini" onclick="deleteProduct('${x.id}')">Delete</button></div></div>`).join(""):`<div class="empty">No products yet.<br>Add one or import a CSV.</div>`}
async function renderSend(cs,ps){let c=$("sendContact"),p=$("sendProduct"),oldc=c.value,oldp=p.value;c.innerHTML=`<option value="">Select contact</option>`+cs.map(x=>`<option value="${x.id}">${esc(x.name)} · ${esc(x.phone)}</option>`).join("");p.innerHTML=`<option value="">Select product</option>`+ps.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("");if(cs.some(x=>x.id===oldc))c.value=oldc;if(ps.some(x=>x.id===oldp))p.value=oldp;updateMessage()}
async function updateMessage(){let cs=await all("contacts"),ps=await all("products"),c=cs.find(x=>x.id===$("sendContact").value),p=ps.find(x=>x.id===$("sendProduct").value);if(!c||!p){$("message").value="";return}$("message").value=`🔥 *Deal Alert!*\n\nHi ${c.name} 👋\n\nCheck out this amazing deal:\n🛍️ *${p.name}*\n${p.price?`💰 ₹${p.price}\n`:""}${p.description?`\n${p.description}\n`:""}\n🔗 Buy Now: ${p.link}\n\nHappy Shopping! ❤️`}
function renderHistory(hs){hs.sort((a,b)=>b.time-a.time);$("historyList").innerHTML=hs.length?hs.map(x=>`<div class="item"><div><h3>${esc(x.contactName)} · ${esc(x.productName)}</h3><p>${new Date(x.time).toLocaleString()}</p><p>${esc(x.phone)}</p></div></div>`).join(""):`<div class="empty">No messages sent yet.</div>`}

function modal(title,html,onSubmit){$("modalTitle").textContent=title;$("modalForm").innerHTML=html+`<button class="primary big" type="submit">Save</button>`;$("modal").hidden=false;$("modalForm").onsubmit=async e=>{e.preventDefault();await onSubmit(new FormData(e.target));$("modal").hidden=true;await render(document.querySelector(".page.active").id)}}
function addContact(existing){let x=existing||{name:"",phone:"",category:"General"};modal(existing?"Edit Contact":"Add Contact",`<label>Name<input name="name" required value="${esc(x.name)}"></label><label>WhatsApp Number<input name="phone" required inputmode="tel" placeholder="919876543210" value="${esc(x.phone)}"></label><label>Category<input name="category" value="${esc(x.category)}"></label>`,async f=>put("contacts",{id:x.id||uid(),name:f.get("name").trim(),phone:f.get("phone").replace(/[^0-9]/g,""),category:f.get("category").trim()}))}
function addProduct(existing){let x=existing||{name:"",description:"",price:"",platform:"Amazon",link:""};modal(existing?"Edit Product":"Add Product",`<label>Product Name<input name="name" required value="${esc(x.name)}"></label><label>Description<textarea name="description">${esc(x.description)}</textarea></label><label>Price<input name="price" inputmode="decimal" value="${esc(x.price)}"></label><label>Platform<select name="platform">${["Amazon","Flipkart","Nykaa","Myntra","Other"].map(v=>`<option ${x.platform===v?"selected":""}>${v}</option>`).join("")}</select></label><label>Product Link<input name="link" type="url" required value="${esc(x.link)}"></label>`,async f=>put("products",{id:x.id||uid(),name:f.get("name").trim(),description:f.get("description").trim(),price:f.get("price").trim(),platform:f.get("platform"),link:f.get("link").trim()}))}
window.editContact=async id=>addContact((await all("contacts")).find(x=>x.id===id));window.deleteContact=async id=>{if(confirm("Delete this contact?")){await del("contacts",id);renderContacts(await all("contacts"));render("dashboard")}};
window.editProduct=async id=>addProduct((await all("products")).find(x=>x.id===id));window.deleteProduct=async id=>{if(confirm("Delete this product?")){await del("products",id);renderProducts(await all("products"));render("dashboard")}};

function parseCSV(text){let rows=[],row=[],cell="",quote=false;for(let i=0;i<text.length;i++){let ch=text[i],n=text[i+1];if(ch==='"'&&quote&&n==='"'){cell+='"';i++;continue}if(ch==='"'){quote=!quote;continue}if(ch===','&&!quote){row.push(cell);cell="";continue}if((ch==='\n'||ch==='\r')&&!quote){if(ch==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell="";continue}cell+=ch}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows}
async function importCSV(file,type){let rows=parseCSV(await file.text());if(!rows.length)return;let headers=rows.shift().map(x=>x.trim().toLowerCase());for(const r of rows){let o={};headers.forEach((h,i)=>o[h]=r[i]||"");if(type==="contacts"){let name=o.name||o["full name"],phone=o.phone||o["whatsapp number"]||o.number;if(name&&phone)await put("contacts",{id:uid(),name,phone:phone.replace(/[^0-9]/g,""),category:o.category||"General"})}else{let name=o.name||o["product name"],link=o.link||o["product link"]||o.url;if(name&&link)await put("products",{id:uid(),name,description:o.description||"",price:o.price||"",platform:o.platform||"Other",link})}}alert("Import completed.");showPage(type==="contacts"?"contacts":"products")}
$("addContact").onclick=()=>addContact();$("addProduct").onclick=()=>addProduct();$("closeModal").onclick=()=>{$("modal").hidden=true};
$("contactSearch").oninput=()=>renderContacts([]).then(async()=>renderContacts(await all("contacts")));$("productSearch").oninput=()=>renderProducts([]).then(async()=>renderProducts(await all("products")));
$("sendContact").onchange=updateMessage;$("sendProduct").onchange=updateMessage;
$("openWhatsApp").onclick=async()=>{let cs=await all("contacts"),ps=await all("products"),c=cs.find(x=>x.id===$("sendContact").value),p=ps.find(x=>x.id===$("sendProduct").value),m=$("message").value.trim();if(!c||!p||!m)return alert("Select a contact and product first.");let phone=c.phone.replace(/\D/g,"");if(phone.length<10)return alert("Please enter a valid WhatsApp number with country code, e.g. 919876543210.");await put("history",{id:uid(),contactName:c.name,phone,productName:p.name,time:Date.now(),message:m});window.location.href=`https://wa.me/${phone}?text=${encodeURIComponent(m)}`;render("history")};
$("clearHistory").onclick=async()=>{if(confirm("Clear message history?")){await clear("history");render("history")}};
$("exportData").onclick=async()=>{let data={version:1,exportedAt:new Date().toISOString(),contacts:await all("contacts"),products:await all("products"),history:await all("history")};let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="deal-dhamaka-backup.json";a.click()};
$("importData").onchange=async e=>{let f=e.target.files[0];if(!f)return;let d=JSON.parse(await f.text());for(const x of d.contacts||[])await put("contacts",x);for(const x of d.products||[])await put("products",x);for(const x of d.history||[])await put("history",x);alert("Backup imported.");showPage("dashboard")};
$("importCsvContacts").onclick=()=>{$("contactsCsv").click()};$("contactsCsv").onchange=e=>importCSV(e.target.files[0],"contacts");
$("importCsvProducts").onclick=()=>{$("productsCsv").click()};$("productsCsv").onchange=e=>importCSV(e.target.files[0],"products");
$("resetData").onclick=async()=>{if(confirm("This will delete ALL contacts, products and history on this device. Continue?")){await Promise.all(["contacts","products","history"].map(clear));showPage("dashboard")}};
document.querySelectorAll(".tabbar button,[data-page]").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
let deferred;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;$("installBtn").hidden=false});$("installBtn").onclick=async()=>{if(deferred){deferred.prompt();deferred=null;$("installBtn").hidden=true}};
openDB().then(()=>showPage("dashboard"));
